### ISSUE TITLE
Ayuda por favor

### ISSUE THREAD

**Issue by 2k-kun** [Yizack/yeezac#8]
Hola Yizack, soy alguien nuevito en esto de la programacion y si bien segui tus pasos me sale el sig. error

SyntaxError: C:\Users\2k\Documents\Bot discord\2ktan bot\config.json: Unexpected token } in JSON at position 239
    at parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1185:22)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1040:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\2k\Documents\Bot discord\2ktan bot\index.js:3:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1151:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)[39m

Exactamente como podria solucionar el problema?

**Comment by Yizack** [comment]
Hola parece que la ejecución te manda un error de syntaxis en tu archivo `config.json`, fijate a ver si está correctamente escrito, según el error debería ser porque tienes dos llaves "`}}`" al final del código de tu archivo.
